services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ktaxes
    ports:
      - '5432:5432'
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
